cedricziel/idea-php-typo3-plugin

- META-INF/plugin.xml
- README.md
- src/com/cedricziel/idea/typo3/annotation/RouteAnnotator.java
- src/com/cedricziel/idea/typo3/codeInsight/RouteLineMarkerProvider.java
- src/com/cedricziel/idea/typo3/container/RouteProvider.java
- src/com/cedricziel/idea/typo3/domain/TYPO3RouteDefinition.java
- src/com/cedricziel/idea/typo3/psi/visitor/RouteDefinitionParserVisitor.java
The annotator marks valid and invalid route references visually:
The marker provider marks the line with the literal epression and allows the user to jump directly to the definition:
> Add route annotator and line marker provider

- src/com/cedricziel/idea/typo3/annotation/IconAnnotator.java
Icons added in an extensions currently can't be resolved, so it would be nicer to trigger a warning instead of an error.
> Add warning instead of an error on missing icons

- src/main/java/com/cedricziel/idea/typo3/annotation/PathResourceAnnotator.java
- src/main/java/com/cedricziel/idea/typo3/codeInsight/PathResourceCompletionContributor.java
- src/main/resources/META-INF/plugin.xml
Every PHP String now supports the `EXT:` file Syntax and the IDE will autocomplete the path.
> Add support for `EXT:foo/bar/..` syntax

- src/main/java/com/cedricziel/idea/typo3/codeInsight/PathResourceCompletionContributor.java
- src/main/java/com/cedricziel/idea/typo3/codeInsight/navigation/PathResourceGotoDeclarationHandler.java
- src/main/java/com/cedricziel/idea/typo3/util/ResourceUtil.java
- src/main/resources/META-INF/plugin.xml
Users can now use "go to declaration" on "EXT:foo" resource paths and the IDE will propose matching elements.
> Introduce PathResourceGotoDeclarationHandler

- src/main/java/com/cedricziel/idea/typo3/index/TablenameFileIndex.java
- src/main/java/com/cedricziel/idea/typo3/util/TableUtil.java
- src/main/resources/META-INF/plugin.xml
The tablename index does one thing: Store text-ranges where a tables' definitions are.
It does so by saving a TextRange into the index and on access it pin-points directly to the element so we can find a PsiElement at the given position.
> Introduce Tablename Index and use it

- .travis.yml
- build.gradle
- src/main/java/com/cedricziel/idea/typo3/annotation/PathResourceAnnotator.java
- src/main/java/com/cedricziel/idea/typo3/codeInsight/PathResourceCompletionContributor.java
- src/main/java/com/cedricziel/idea/typo3/codeInsight/navigation/PathResourceGotoDeclarationHandler.java
- src/main/java/com/cedricziel/idea/typo3/index/ResourcePathIndex.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/cedricziel/idea/typo3/codeInsight/PathResourceCompletionContributorTest.java
- src/test/java/com/cedricziel/idea/typo3/index/ResourcePathIndexTest.java
- src/test/java/com/cedricziel/idea/typo3/util/ResourceUtilTest.java
DirectoryScanner is only available in IntelliJ and breaks resource discovery in PHPStorm.
This PR moves away from it and indexes all available resource files and then instead of dynamically collecting available files queris the index for its keys.
Fixes: #82
> Use ScalarIndexExtension instead of DirectoryScanner

- src/main/java/com/cedricziel/idea/typo3/index/ResourcePathIndex.java
- src/main/java/com/cedricziel/idea/typo3/util/ComposerUtil.java
- src/test/java/com/cedricziel/idea/typo3/index/ResourcePathIndexTest.java
This should allow unconventional paths in a project. The plugin can now detect extension root paths by finding ext_emconf.php files and analyzing sibling composer.json files.
A proper TYPO3 extensions' `composer.json` looks like this:
```json
{
"name": "package/foo", // priority 3
"bar": "baz",
"type": "typo3-cms-extension", // *mandatory*
"extra": {
"installerName": "foo_bar_baz", // Priority 2
"typo3/cms": {
"extension-key": "my_key" // Priority 1
}
}
}
```
Please note that the `type` key is needed to properly detect the package.
[TYPO3 CMS Plugin-v0.2.20-1-g78f78a6.zip](https://github.com/cedricziel/idea-php-typo3-plugin/files/1500307/TYPO3.CMS.Plugin-v0.2.20-1-g78f78a6.zip)
Resolves: #87
> Resolve extension-keys from unconventional paths

- src/main/java/com/cedricziel/idea/typo3/codeInsight/navigation/PathResourceGotoDeclarationHandler.java
- src/main/java/com/cedricziel/idea/typo3/index/ResourcePathIndex.java
This checks for existence of a folder resource.
[TYPO3 CMS Plugin-v0.2.21-1-g3f2006f.zip](https://github.com/cedricziel/idea-php-typo3-plugin/files/1501834/TYPO3.CMS.Plugin-v0.2.21-1-g3f2006f.zip)
Resolves: #89
> Allow resolving resource paths with trailing slashes

- src/main/java/com/cedricziel/idea/typo3/codeInsight/RouteLineMarkerProvider.java
[TYPO3 CMS Plugin-v0.2.28-1-g982fefd.dirty.zip](https://github.com/cedricziel/idea-php-typo3-plugin/files/1527150/TYPO3.CMS.Plugin-v0.2.28-1-g982fefd.dirty.zip)
Fixes: #109
> Fix RouteLineMarker by calling setTargets

- build.gradle
- src/main/java/com/cedricziel/idea/typo3/resources/ResourceReference.java
- src/main/java/com/cedricziel/idea/typo3/resources/ResourceReferenceContributor.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/cedricziel/idea/typo3/resources/php/ResourceReferenceContributorTest.java
- src/test/java/com/cedricziel/idea/typo3/resources/yaml/ResourceReferenceContributorTest.java
This adds the ability to reference `EXT:` strings in YAML files.
Example:
```yaml
imports:
- { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" } 
```
Ref: #51
> Autocomplete and cross-reference resources in YAML files

- .travis.yml
- build.gradle
- gradle.properties
- src/main/java/com/cedricziel/idea/typo3/codeInspection/MissingColumnTypeInspection.java
- src/main/java/com/cedricziel/idea/typo3/tca/TCAPatterns.java
- src/main/java/com/cedricziel/idea/typo3/tca/codeInsight/TCACompletionContributor.java
- src/main/java/com/cedricziel/idea/typo3/userFunc/UserFuncInsertHandler.java
- src/main/java/com/cedricziel/idea/typo3/userFunc/UserFuncLookupElement.java
- src/main/java/com/cedricziel/idea/typo3/userFunc/UserFuncPatterns.java
- src/main/java/com/cedricziel/idea/typo3/userFunc/UserFuncReference.java
- src/main/java/com/cedricziel/idea/typo3/userFunc/UserFuncReferenceContributor.java
- src/main/java/com/cedricziel/idea/typo3/util/TCAUtil.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/cedricziel/idea/typo3/AbstractTestCase.java
- src/test/java/com/cedricziel/idea/typo3/tca/codeInsight/TCACompletionContributorTest.java
- src/test/java/com/cedricziel/idea/typo3/userFunc/UserFuncReferenceContributorTest.java
- src/test/java/com/cedricziel/idea/typo3/userFunc/UserFuncReferenceTest.java
- testData/com/cedricziel/idea/typo3/userFunc/classes.php
- testData/com/cedricziel/idea/typo3/userFunc/foo.php
Enable code navigation between usage and definition in:
**PHP:**
```php
['userFunc' => 'my_function'],
['itemsProcFunc' => 'my_function'],
```
**XML:**
```xml
<userFunc>my_function</userFunc>
<itemsProcFunc>myFunction</userFunc>
```
Handling TypoScript will be possible, once the TypoScript plugin is compatible.
Closes: #188
> Handle userFunc references

- lang-fluid/src/main/grammars/FluidParser.bnf
- lang-fluid/src/test/java/com/cedricziel/idea/fluid/lang/parser/ParserTest.java
Simple arrays can be embedded in arguments:
```html
<bar:baz args="{arg1: 'val', 'arg2': value}"/>
```
> [Fluid] Parse simple inline arrays

- lang-fluid/build.gradle
- lang-fluid/src/main/java/com/cedricziel/idea/fluid/codeInsight/template/LiveTemplateFactory.java
- lang-fluid/src/main/java/com/cedricziel/idea/fluid/codeInsight/template/postfix/templates/DebugInlinePostfixTemplate.java
- lang-fluid/src/main/java/com/cedricziel/idea/fluid/codeInsight/template/postfix/templates/FluidPostfixTemplateProvider.java
- lang-fluid/src/main/java/com/cedricziel/idea/fluid/codeInsight/template/postfix/templates/ForEachPostfixTemplate.java
- lang-fluid/src/main/java/com/cedricziel/idea/fluid/util/FluidUtil.java
- lang-fluid/src/main/java/icons/FluidIcons.java
- lang-fluid/src/main/resources/META-INF/change-notes.html
- lang-fluid/src/main/resources/META-INF/description.html
- lang-fluid/src/main/resources/postfixTemplates/DebugInlinePostfixTemplate/after.fluid.html
- lang-fluid/src/main/resources/postfixTemplates/DebugInlinePostfixTemplate/before.fluid.html
- lang-fluid/src/main/resources/postfixTemplates/DebugInlinePostfixTemplate/description.html
- lang-fluid/src/test/java/com/cedricziel/idea/fluid/codeInsight/template/postfix/templates/AbtractTemplateTest.java
- lang-fluid/src/test/java/com/cedricziel/idea/fluid/codeInsight/template/postfix/templates/DebugInlinePostfixTemplateTest.java
- lang-fluid/src/test/java/com/cedricziel/idea/fluid/codeInsight/template/postfix/templates/ForEachPostfixTemplateTest.java
- lang-fluid/testData/com/cedricziel/idea/fluid/codeInsight/template/postfix/debugTemplate.fluid
- lang-fluid/testData/com/cedricziel/idea/fluid/codeInsight/template/postfix/debugTemplate_after.fluid
- lang-fluid/testData/com/cedricziel/idea/fluid/codeInsight/template/postfix/foreachTemplate.fluid
- lang-fluid/testData/com/cedricziel/idea/fluid/codeInsight/template/postfix/foreachTemplate_after.fluid
- lang-typoscript/build.gradle
- lang-typoscript/src/main/resources/META-INF/change-notes.html
- lang-typoscript/src/main/resources/META-INF/description.html
- prepare-release.sh
- typo3-cms/build.gradle
- typo3-cms/src/main/resources/META-INF/change-notes.html
- typo3-cms/src/main/resources/META-INF/description.html
Changes the string template to a live template.
* adds a changelog tool
* fixes an error with 2018.1 where icons are not correctly resolved.
> Live template for f:for

- lang-fluid/src/main/grammars/FluidLexer.flex
- lang-fluid/src/main/grammars/FluidParser.bnf
- lang-fluid/src/test/java/com/cedricziel/idea/fluid/namespaces/InlineNSNamespaceProviderTest.java
- lang-fluid/src/test/java/com/cedricziel/idea/fluid/viewHelpers/PhpViewHelpersProviderTest.java
Up until now, a namespace alias with multiple chars (`app`) were not
possible.
This changeset compliments the lexer to accept it, with a new parsing
state.
```
{namespace app=My\Project\ViewHelpers}
```
> [Fluid] Lex multi-char namespace imports correctly

- typo3-cms/src/main/java/com/cedricziel/idea/typo3/translation/annotation/TranslationAnnotator.java
- typo3-cms/src/test/java/com/cedricziel/idea/typo3/translation/annotation/TranslationAnnotatorTest.java
Also switches error annotation to weak warning.
> Don't annotate translation strings under concatenation

- typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSIcons.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3Patterns.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/dispatcher/SignalDispatcherReferenceContributor.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/dispatcher/SignalSlotMethodReference.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/SignalSlotDispatcherUtil.java
- typo3-cms/src/main/resources/META-INF/plugin.xml
- typo3-cms/src/test/java/com/cedricziel/idea/typo3/dispatcher/SignalDispatcherReferenceContributorTest.java
- typo3-cms/testData/com/cedricziel/idea/typo3/dispatcher/classes.php
Allows seamless navigation between slot methods and their reference.
Enables stable, name-based refactoring of slot method names.
Closes: #55
Closes: #67
> [T3CMS] Contribute Signal/Slot References to slot methods

- typo3-cms/src/main/java/com/cedricziel/idea/typo3/IdeHelper.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectComponent.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectSettings.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSSettings.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/configuration/TYPO3CMSSettingsForm.form
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/configuration/TYPO3CMSSettingsForm.java
- typo3-cms/src/main/resources/META-INF/plugin.xml
To resolve some issues and enable customization, this change introduces
project settings and most importantly a way to enable / disable
the plugin functionality for a project.
The TYPO3CMSProjectComponent tries to detect a TYPO3 CMS project and
proposes to enable itself.
Followups should include enabling / disabling inspections and other
features based on this setting which should slightly improve performance
in projects that don't need the functionality.
> [T3CMS] Introduce project settings

- typo3-cms/src/main/java/com/cedricziel/idea/typo3/tca/codeInspection/v10/InternalTypeFileInspection.java
- typo3-cms/src/main/resources/META-INF/plugin.xml
- typo3-cms/src/test/java/com/cedricziel/idea/typo3/tca/codeInspection/v10/InternalTypeFileInspectionTest.java
- typo3-cms/testData/com/cedricziel/idea/typo3/tca/codeInspection/v10/invalid_internal_type_disabled.php
- typo3-cms/testData/com/cedricziel/idea/typo3/tca/codeInspection/v10/invalid_internal_type_v10.php
- typo3-cms/testData/com/cedricziel/idea/typo3/tca/codeInspection/v10/invalid_internal_type_v8.php
- typo3-cms/testData/com/cedricziel/idea/typo3/tca/codeInspection/v10/invalid_internal_type_v9.php
The TCA option `internal_type` will have the options `file` and `file_reference` deprecated in v9 and removed in v10.
> [T3CMS] Add Inspection for invalid internal_type TCA option on v9 and up

- typo3-cms/src/main/java/com/cedricziel/idea/typo3/extbase/persistence/ExtbasePersistenceReferenceResolver.java
The unstable (my fault for falling into the trap) ReferenceResolver
changed in 2019.3 and wants its candidates back.
Fixes a severe issue where no class is resolved at all.
Fixes: #298
> [T3CMS] Return candidates when resolving references

- lang-fluid/src/main/java/com/cedricziel/idea/fluid/util/FluidUtil.java
- typo3-cms/src/main/java/com/cedricziel/idea/typo3/codeInspection/UnusedActionControllerMethodInspectionSuppressor.java
- typo3-cms/src/main/resources/META-INF/plugin.xml
- typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/UnusedActionControllerMethodInspectionSuppressorTest.java
- typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/action_controller.php
- typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/classes.php
* classes implementing ControllerInterface and
* methods in such classes with an `Action` suffix
wont be marked as unused anymore.
Closes: #291
> [T3CMS] Suppress unused inspection for extbase controllers
