META-INF/plugin.xml, README.md, src/com/cedricziel/idea/typo3/provider/ObjectManagerTypeProvider.java
=> Add ObjectManagerTypeResolver

META-INF/plugin.xml, src/com/cedricziel/idea/typo3/TYPO3CMSProjectComponent.java, src/com/cedricziel/idea/typo3/annotation/IconAnnotator.java, src/com/cedricziel/idea/typo3/codeInsight/IconCompletionContributor.java, src/com/cedricziel/idea/typo3/codeInsight/IconLineMarkerProvider.java, src/com/cedricziel/idea/typo3/container/IconProvider.java, src/com/cedricziel/idea/typo3/container/RouteProvider.java, src/com/cedricziel/idea/typo3/domain/TYPO3IconDefinition.java, src/com/cedricziel/idea/typo3/psi/visitor/CoreIconParserVisitor.java, src/com/cedricziel/idea/typo3/util/IconUtil.java
Needs followup: Re-Collect icons every now and then
@coding46 can you provide a default icon for icons that could not be resolved?
=> Display IconLineMarker and collect icons on startup

META-INF/plugin.xml, src/com/cedricziel/idea/typo3/provider/PhpGlobalsTypeProvider.java
=> Add TypeProvider for $GLOBALS TYPO3_DB, TSFE and BE_USER

src/com/cedricziel/idea/typo3/TYPO3CMSProjectComponent.java, src/com/cedricziel/idea/typo3/annotation/IconAnnotator.java, src/com/cedricziel/idea/typo3/codeInsight/IconCompletionContributor.java, src/com/cedricziel/idea/typo3/codeInsight/IconLineMarkerProvider.java, src/com/cedricziel/idea/typo3/codeInsight/extbase/EntityLineMarkerProvider.java, src/com/cedricziel/idea/typo3/container/IconProvider.java, src/com/cedricziel/idea/typo3/generation/action/GenerateFscElementForm.java
* cope providers by project
This should greatly improve the stability since now only one provider is created at a time and
every project has its own icon provider now.
=> Synchronize instance creation of IconProvider

src/com/cedricziel/idea/typo3/codeInsight/IconCompletionContributor.java, src/com/cedricziel/idea/typo3/codeInsight/IconLineMarkerProvider.java, src/com/cedricziel/idea/typo3/container/IconProvider.java, src/com/cedricziel/idea/typo3/domain/TYPO3IconDefinition.java, src/com/cedricziel/idea/typo3/generation/action/GenerateFscElementForm.java, src/com/cedricziel/idea/typo3/psi/visitor/CoreFlagParserVisitor.java, src/com/cedricziel/idea/typo3/psi/visitor/CoreIconParserVisitor.java, src/com/cedricziel/idea/typo3/util/IconUtil.java
=> Collect system flag icons

.travis.yml, META-INF/plugin.xml, src/com/cedricziel/idea/typo3/util/ExtensionFileGenerationUtil.java, travis.sh
=> Prevent NPE on element creation

src/main/java/com/cedricziel/idea/typo3/index/ExtensionIndex.java, src/main/java/com/cedricziel/idea/typo3/index/ExtensionNameStubIndex.java, src/main/java/com/cedricziel/idea/typo3/index/externalizer/ObjectStreamDataExternalizer.java, src/main/resources/META-INF/plugin.xml
This index maps an extension key inferred from a path segment to its `ext_emconf.php` file.
=> Implement ExtensionNameStubIndex

src/main/java/com/cedricziel/idea/typo3/annotation/PathResourceAnnotator.java
Instead of error annotation
Resolves: #91
=> Create warning annotation for missing resources

src/main/java/com/cedricziel/idea/typo3/action/AbstractDumbAwareAction.java, src/main/java/com/cedricziel/idea/typo3/action/GenerateFscElementAction.java, src/main/java/com/cedricziel/idea/typo3/action/GenerateFscElementForm.form, src/main/java/com/cedricziel/idea/typo3/action/GenerateFscElementForm.java, src/main/java/com/cedricziel/idea/typo3/action/GenerateViewHelperAction.java, src/main/java/com/cedricziel/idea/typo3/action/NewExtensionFileAction.java, src/main/java/com/cedricziel/idea/typo3/index/ResourcePathIndex.java, src/main/java/com/cedricziel/idea/typo3/util/ComposerUtil.java, src/main/java/com/cedricziel/idea/typo3/util/ExtensionFileGenerationUtil.java, src/main/java/com/cedricziel/idea/typo3/util/ExtensionUtility.java, src/main/java/com/cedricziel/idea/typo3/util/FilesystemUtil.java, src/main/java/com/cedricziel/idea/typo3/util/TYPO3Utility.java, src/main/resources/META-INF/plugin.xml, src/main/resources/fileTemplates/extension_file/7/ViewHelper.php, src/main/resources/fileTemplates/extension_file/8/ViewHelper.php, src/main/resources/fileTemplates/extension_file/9/ViewHelper.php, src/main/resources/fileTemplates/extension_file/ViewHelper.php
[TYPO3 CMS Plugin-v0.2.23-9-gc1dba1f.zip](https://github.com/cedricziel/idea-php-typo3-plugin/files/1504239/TYPO3.CMS.Plugin-v0.2.23-9-gc1dba1f.zip)
=> Add "Create ViewHelper" action

src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectComponent.java, src/main/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionInterface.java, src/main/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionLookupElement.java, src/main/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionReference.java, src/main/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionReferenceContributor.java, src/main/java/com/cedricziel/idea/typo3/extbase/controller/StubControllerAction.java, src/main/java/com/cedricziel/idea/typo3/index/extbase/ControllerActionIndex.java, src/main/java/com/cedricziel/idea/typo3/util/ControllerActionUtil.java, src/main/java/com/cedricziel/idea/typo3/util/ExtensionUtility.java, src/main/java/com/cedricziel/idea/typo3/util/PhpLangUtil.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionReferenceProviderTest.java, src/test/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionReferenceTest.java, src/test/java/com/cedricziel/idea/typo3/index/extbase/ControllerActionIndexTest.java, testData/com/cedricziel/idea/typo3/index/extbase/FooController.php
This allows navigating through extbase controller actions.
Closes: #73
=> Add Extbase ControllerActionReference

src/main/java/com/cedricziel/idea/typo3/action/ExtbaseControllerActionAction.java, src/main/java/com/cedricziel/idea/typo3/action/NewExtensionFileAction.java
=> Raise dumb-awareness for code-generating actions

src/main/java/com/cedricziel/idea/typo3/annotation/RouteAnnotator.java, src/main/java/com/cedricziel/idea/typo3/routing/RouteParserVisitor.java, src/main/java/com/cedricziel/idea/typo3/routing/RouteStub.java, src/test/java/com/cedricziel/idea/typo3/icons/IconReferenceProviderTest.java, src/test/java/com/cedricziel/idea/typo3/index/IconIndexTest.java, src/test/java/com/cedricziel/idea/typo3/index/RouteIndexTest.java, testData/com/cedricziel/idea/typo3/index/route/BackendRoutes.php, testData/com/cedricziel/idea/typo3/index/route/Routes.php
* simplifies the annotator to match on strings with RouteReference references
* reimplement RouteParserVisitor
=> Correctly re-implement route indexing

src/main/java/com/cedricziel/idea/typo3/codeInspection/MissingTableInspection.java
=> Don't annotate wildcard allowed tables in TCA as missing

src/main/java/com/cedricziel/idea/typo3/action/GenerateExtbaseEntityAction.java
=> Generate new entity to Entity sub-namespace

README.md
I've created a [Patreon page](https://www.patreon.com/cedricziel) where interested people can support the further development of the plugin.
=> Add Patreon to Readme

src/main/java/com/cedricziel/idea/typo3/TYPO3CMSIcons.java, src/main/java/com/cedricziel/idea/typo3/index/IconIndex.java, src/main/java/com/cedricziel/idea/typo3/index/ResourcePathIndex.java, src/main/java/com/cedricziel/idea/typo3/resources/ResourceReferenceContributor.java, src/main/java/com/cedricziel/idea/typo3/translation/annotation/TranslationAnnotator.java, src/main/java/com/cedricziel/idea/typo3/translation/codeInspection/TranslationMissingInspection.java, src/test/java/com/cedricziel/idea/typo3/index/ResourcePathIndexTest.java
=> Do not error on translation file references

src/main/java/com/cedricziel/idea/typo3/psi/PhpElementsUtil.java, src/test/java/com/cedricziel/idea/typo3/psi/PhpElementsUtilTest.java
=> Detect superclasses through PhpClassHierarchyUtils rather than own code

src/main/java/com/cedricziel/idea/typo3/translation/annotation/TranslationAnnotator.java, src/main/java/com/cedricziel/idea/typo3/translation/codeInspection/TranslationMissingInspection.java, src/test/java/com/cedricziel/idea/typo3/AbstractTestCase.java, src/test/java/com/cedricziel/idea/typo3/index/TranslationIndexTest.java, src/test/java/com/cedricziel/idea/typo3/translation/AbtractTranslationTest.java, src/test/java/com/cedricziel/idea/typo3/translation/TranslationReferenceProviderTest.java, src/test/java/com/cedricziel/idea/typo3/translation/TranslationReferenceTest.java, src/test/java/com/cedricziel/idea/typo3/translation/annotation/TranslationAnnotatorTest.java, src/test/java/com/cedricziel/idea/typo3/translation/codeInspection/TranslationMissingInspectionTest.java, src/test/java/com/cedricziel/idea/typo3/util/TranslationUtilTest.java
=> Dont check translation strings ending with a colon

typo3-cms/src/main/java/com/cedricziel/idea/typo3/index/TablenameFileIndex.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/index/TablenameIndexTest.java
=> Expand table name regex to match quoted identifiers

README.md
YourKit kindly sponsors the its Java Profiler for the project.
=> Add YourKit as a sponsor

lang-fluid/src/main/java/com/cedricziel/idea/fluid/codeInsight/ControllerLineMarkerProvider.java, lang-fluid/src/main/java/com/cedricziel/idea/fluid/codeInsight/TemplateLineMarkerProvider.java, lang-fluid/src/main/java/com/cedricziel/idea/fluid/completion/FluidCompletionContributor.java, lang-fluid/src/main/java/com/cedricziel/idea/fluid/util/FluidUtil.java, lang-fluid/src/main/java/com/cedricziel/idea/fluid/variables/provider/ControllerVariableProvider.java, lang-fluid/src/main/java/icons/FluidIcons.java, lang-fluid/src/main/resources/META-INF/php-support.xml
Line markers in template and controller action to allow navigating between templates and controller action:
Template line marker:
Controller line marker:
=> Add Template line marker

typo3-cms/src/main/java/com/cedricziel/idea/typo3/index/ResourcePathIndex.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/resources/ResourceReference.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/ResourceUtil.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TCAUtil.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TranslationUtil.java
* apply local caches to ResourcePathIndex
* apply local caches to TranslationUtil for keys
* apply cached value to available render types
Closes: #209
=>  [T3CMS] Improve performance of Resource and Translation lookups

typo3-cms/src/main/java/com/cedricziel/idea/typo3/translation/codeInspection/TranslationMissingInspection.java
=> [T3CMS] Mark missing translation as generic warning not as error

typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectSettings.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/codeInsight/navigation/PathResourceGotoDeclarationHandler.java
=> [T3CMS] Fix NPE in PathResourceGotoDeclarationHandler

typo3-cms/src/main/java/com/cedricziel/idea/typo3/codeInspection/MissingColumnTypeInspection.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/tca/codeInsight/TCACompletionContributor.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TCAUtil.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/MissingColumnTypeInspectionTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/MissingColumnTypeSlugIsMarkedOnV8.php, typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/MissingColumnTypeSlugIsNotMarkedOnV9.php
=> Add TCA type slug

typo3-cms/src/main/java/com/cedricziel/idea/typo3/flexform/FlexFormCompletionContributionProvider.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TableUtil.java, typo3-cms/src/main/resources/META-INF/plugin.xml, typo3-cms/src/test/java/com/cedricziel/idea/typo3/flexform/FlexFormCompletionContributionProviderTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/flexform/ext_tables.sql, typo3-cms/testData/com/cedricziel/idea/typo3/flexform/flexform_rendertype.xml, typo3-cms/testData/com/cedricziel/idea/typo3/flexform/flexform_tablename.xml, typo3-cms/testData/com/cedricziel/idea/typo3/flexform/flexform_type.xml
* complete render types
* complete field types (#185)
* complete table names (#183)
Closes: #185 
Closes: #183
=> Enhance completion for FlexForms

typo3-cms/src/main/java/com/cedricziel/idea/typo3/contextApi/ContextTypeProvider.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/extbase/persistence/ExtbaseModelCollectionReturnTypeProvider.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/provider/AbstractServiceLocatorTypeProvider.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/provider/PhpGlobalsTypeProvider.java, typo3-cms/src/main/resources/META-INF/plugin.xml
PhpTypeProvider3 is deprecated.
=> Upgrade TypeProviders to PhpTypeProvider4

typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/ExtbasePropertyInjectionInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/LegacyClassesForIDEInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/MissingColumnTypeInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/MissingRenderTypeInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/MissingTableInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/provider/ObjectManagerTypeProviderTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/provider/classes.php
=> [T3CMS] Add additional test for ObjectManagerGet TypeProvider

typo3-cms/src/main/java/com/cedricziel/idea/typo3/index/TranslationIndex.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/index/TranslationIndexTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/index/translation/locallang_be.xlf
There was some space for an NPE. The indexing was made more defensive.
Fixes: #285
=> [T3CMS] Prevent possible NPE when indexing translations

typo3-cms/src/test/java/com/cedricziel/idea/typo3/index/RouteIndexTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/index/route/AjaxRoutes.php, typo3-cms/testData/com/cedricziel/idea/typo3/index/route/ajax_route_usage.php
=> [T3CMS] Ensure AjaxRoutes are correctly indexed

typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectComponent.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/codeInspection/PluginEnabledJsInspection.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/javaScript/ModuleProvider.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/javaScript/codeInspection/MissingModuleJSInspection.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/javaScript/codeInspection/MissingModulePHPInspection.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/ExtensionUtility.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/JavaScriptUtil.java, typo3-cms/src/main/resources/META-INF/features-javascript.xml, typo3-cms/src/main/resources/inspectionDescriptions/MissingModuleJS.html, typo3-cms/src/main/resources/inspectionDescriptions/MissingModulePHP.html, typo3-cms/src/test/java/com/cedricziel/idea/typo3/javaScript/ModuleProviderTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/javaScript/codeInspection/MissingModuleJSInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/javaScript/codeInspection/MissingModulePHPInspectionTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/util/JavaScriptUtilTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/classes.php, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/js_module_reference.php, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/js_module_reference_concat.php, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/js_module_reference_invalid.php, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/js_module_reference_invalid_callback.php, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/use_reference.js, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/codeInspection/use_reference_missing.js, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/define_reference.js, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/use_reference.js, typo3-cms/testData/com/cedricziel/idea/typo3/javaScript/use_reference_completion.js
=> [T3CMS] Add support for RequireJS modules

typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectSettings.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSSettings.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/listener/TYPO3DetectionListener.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/listener/XLFFileTypeListener.java, typo3-cms/src/main/resources/META-INF/plugin.xml, typo3-cms/src/test/java/com/cedricziel/idea/typo3/util/PhpTypeProviderUtilTest.java
=> [T3CMS] Migrate project-components to ProjectManagerListeners

typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectSettings.java
=> [T3CMS] Store settings file relatively

typo3-cms/src/main/java/com/cedricziel/idea/typo3/index/TranslationIndex.java
=> [T3CMS] Prevent ArrayOutOfBoundsException on WSL when indexing translations

typo3-cms/src/main/java/com/cedricziel/idea/typo3/TYPO3CMSProjectSettings.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/configuration/TYPO3CMSSettingsForm.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TranslationUtil.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/translation/TranslationFoldingBuilderTest.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/translation/TranslatorTest.java
Works around having to cast raw Objects from the project settings
=> [T3CMS] Rename settings property for translation folding

typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TranslationUtil.java
=> [T3CMS] Create convenience method to get locale

lang-fluid/src/main/java/com/cedricziel/idea/fluid/tagMode/UnboundNamespaceSuppressor.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/codeInsight/navigation/PathResourceGotoDeclarationHandler.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/codeInspection/MissingTableInspection.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/dispatcher/SignalSlotMethodReference.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/extbase/controller/ControllerActionReferenceContributor.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/index/IconIndex.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/routing/RouteFoldingBuilder.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/routing/RouteHelper.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/translation/TranslationFoldingBuilder.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/ControllerActionUtil.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/SignalSlotDispatcherUtil.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TableUtil.java, typo3-cms/src/main/java/com/cedricziel/idea/typo3/util/TranslationUtil.java, typo3-cms/src/test/java/com/cedricziel/idea/typo3/codeInspection/MissingTableInspectionTest.java, typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/MissingTableInspectionIsMarked.php, typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/MissingTableInspectionIsMarkedForAllowed.php, typo3-cms/testData/com/cedricziel/idea/typo3/codeInspection/MissingTableInspectionIsNotMarkedForAllowed.php
=> [T3CMS] `allowed` TCA field can contain CSV string of tables

CHANGELOG.md, gradle.properties, typo3-cms/src/main/java/com/cedricziel/idea/typo3/startup/TYPO3CMSPostStartupActivity.java
=> Move Project detection into read action
